---
version: "2"
services:
  homer:
    image: b4bz/homer
    #To build from source, comment previous line and uncomment below
    #build: .
    container_name: homer
    volumes:
      - /root/homer/public/:/www/assets
    ports:
      - 8080:8080
    user: 0:0 # default
    environment:
      - INIT_ASSETS=1 # default
